name: Actions1 Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Add Checkout Repo
              uses: actions/checkout@v6
              
            - name: Welcome Actions
              run: echo "Actions Test Run"

            - name: List Files
              run: ls

            - name: Read File
              run: cat README.md
        