name: Actions1 Workflow

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay
        run: sudo apt-get install cowsay -y

      - name: Run Cowsay for Dragon
        run: cowsay -f dragon "Dragon check......dscdww" >> dragon.txt
      
      - name: Run Cowsay for Cow
        run: cowsay -f cow "Cow check......dscdww" >> cow.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dragon-artifact
          path: |
            dragon.txt
            cow.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps: 
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: dragon-artifact

      - name: Check dragon
        run: grep -i "dragon" dragon.txt

      - name: Check cow
        run: grep -i "cow" cow.txt
    
  deploy_job_3:
    needs: [build_job_1, test_job_2]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: dragon-artifact

      - name: Read File Dragon
        run: cat dragon.txt

      - name: Read File Cow
        run: cat cow.txt
      
      - name: Deploy File
        run: echo Deploying.......




    # ascii_job:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Add Checkout Repo
    #           uses: actions/checkout@v6

    #         - name: List and Read Files
    #           run: |
    #             echo "Actions Test Run"
    #             ls -ltra
    #             cat README.md
            
    #         - name: Execute Shell Script
    #           run: |
    #             chmod +x ascii-script.sh
    #             ./ascii-script.sh
