name: Actions1 Workflow

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Add Checkout Repo
              uses: actions/checkout@v6

            - name: List and Read Files
              run: |
                echo "Actions Test Run"
                ls -ltra
                cat README.md

            - name : Install Cowsay CLI
              run: sudo apt-get install cowsay -y

            - name: ASCII Artwork
              run: cowsay -f dragon "Dragon check......dscdww" >> dragon.txt 

            - name: Check File Exists
              run: grep -i "dragon" dragon.txt

            - name: Read File
              run: cat dragon.txt

            #- name: List Files
            # run: ls

            #- name: Read File
            # run: cat README.md
        